daily_etl:
  sources:
    api:
      - "etldbprocess"
    postgresql:
      - aisles
      - clients
      - departments
      - location_areas
      - orders
      - products
      - store_types
      - stores
    loadtosilver:
      - aisles
      - clients
      - departments
      - location_areas
      - orders
      - products
      - store_types
      - stores
      - out_of_stock_api     
    loadtodwh:
      - aisles
      - clients
      - departments
      - location_areas
      - orders
      - products
      - store_types
      - stores
      - out_of_stock   